theme="apollo"
taxonomies = [{ name = "tags" }]

[extra]
theme = "auto"
socials = [
  # Configure socials here
  ]
  menu = [
    # Configure menu bar here
    ]

    # See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
